channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - black
  - click
  - einops
  - hydra-core
  - matplotlib
  - numpy
  - pillow
  - pip
  - pytest
  - python=3.10.6
  - python-dotenv
  - pytorch=1.13.0
  - requests
  - sqlite
  - tqdm
