channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - conda-lock
  - black
  - click
  - einops
  - hydra-core
  - matplotlib
  - numpy
  - pip
  - wandb
  - pytest
  - python=3.10
  - python-dotenv
  - pytorch=1.13
  - requests
  - sqlite
  - tqdm
platforms:
  - linux-64
